"""empty message

Revision ID: 358b894b031e
Revises: a47dfd939f0c
Create Date: 2024-07-25 05:51:34.390380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358b894b031e'
down_revision = 'a47dfd939f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
