"""empty message

Revision ID: 766c753258ad
Revises: 7c9483c7f17e
Create Date: 2024-10-04 06:03:33.950828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766c753258ad'
down_revision = '7c9483c7f17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=True),
    sa.Column('code_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code_path', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('codes')
    # ### end Alembic commands ###
