"""empty message

Revision ID: 86ff9fcef2a2
Revises: 144fd69d04cb
Create Date: 2024-10-29 01:59:03.397420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ff9fcef2a2'
down_revision = '144fd69d04cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('assessment_id', sa.String(length=1), nullable=True))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('subject_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('subject_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('assessment_id')
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###
